[pytest]

# Custom Markers
markers =
    high: mark a test as a high priority test.
    medium: mark a test as a medium priority test.
    smoke: mark a test as a smoke test.
    regression: mark a test as a regression test.

# Logging Configuration on Framework Level
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format=%Y-%m-%d %H:%M:%S

# HTML Report Configuration
addopts = -vrA --tb=short --html=reports/report.html --self-contained-html --junitxml=reports/junit_results.xml